version: '3.4'

services:
  TigerFlaskApp:
    image: docker
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 7731"]
    ports:
      - 7731:7731
      - 5678:5678
    environment:
      - FLASK_APP=web-app\index.py
